export default `编辑器使用sublime风格的快捷键，部分快捷键可能与系统快捷键有冲突
"Shift-Tab": "减少缩进",
"Shift-Ctrl-K": "删除当前行",
"Alt-Q": "换行",
"Ctrl-T": "交换光标前后的字符",
"Alt-Left": "向左单位性地移动光标",
"Alt-Right": "向右单位性地移动光标",
"Ctrl-Up": "向上移动卷轴",
"Ctrl-Down": "向下移动卷轴",
"Ctrl-L": "选中当前行",
"Shift-Ctrl-L": "先选中多行，再按下快捷键，会在每行行尾插入光标，即可同时编辑这些行",
"Ctrl-Enter": "向下插入新行",
"Shift-Ctrl-Enter": "向上插入新行",
"Ctrl-D": "选中光标所占的文本，继续操作则会选中下一个相同的文本",
"Shift-Ctrl-Space": "选择代码块内的内容（继续选择父代码块）",
"Shift-Ctrl-M": "选择括号内的内容（继续选择父括号）",
"Ctrl-M": "光标移动至括号内结束或开始的位置",
"Shift-Ctrl-Up": "将光标所在行和上一行代码互换",
"Shift-Ctrl-Down": "将光标所在行和下一行代码互换",
"Ctrl-F": "打开编辑器内置搜索工具，支持正则表达式",
"Ctrl-H": "打开编辑器内置替换工具，支持正则表达式",
"Ctrl-/": "单行注释",
"Ctrl-J": "合并选中的多行代码为一行",
"Shift-Ctrl-D": "复制光标所在整行，插入到下一行",
"F9": "对选中的行进行排序",
"Ctrl-F9": "对选中的行进行非大小写敏感排序",
"Ctrl-K Ctrl-K": "删除当前行光标右侧内容",
"Ctrl-K Ctrl-Backspace": "删除当前行光标左侧内容",
"Ctrl-K Ctrl-U": "将光标所在单词转换为大写形式",
"Ctrl-K Ctrl-L": "将光标所在单词转换为小写形式",
"Ctrl-K Ctrl-0": "展开全部代码",
"Ctrl-K Ctrl-J": "展开全部代码",
"Ctrl-Alt-Up": "向上添加多行光标，可同时编辑多行",
"Ctrl-Alt-Down": "向下添加多行光标，可同时编辑多行",
"Ctrl-F3": "向下寻找匹配项",
"Shift-Ctrl-F3": "向上寻找匹配项",
"Alt-F3": "寻找全部匹配项",
"Shift-Ctrl-[": "折叠代码",
"Shift-Ctrl-]": "展开代码",
"F3": "寻找下一个匹配项",
"Shift-F3": "向上寻找下一个匹配项",
`;
